### ISSUE TITLE
Ошибка API - v (version) is required

### ISSUE THREAD

**Issue by sozidatel** [Rast1234/vkd#9]
```
Traceback (most recent call last):
  File "./main.py", line 255, in <module>
    main()
  File "./main.py", line 184, in main
    (response, json_stuff) = call_api("wall.get", [("owner_id", args.id), ("count", 1), ("offset", 0)], args)
  File "/Users/soz/Social Backups/vkd/Api.py", line 61, in call_api
    raise RuntimeError(msg)
RuntimeError: API call resulted in error (8): Invalid request: v (version) is required
```

**Comment by Rast1234** [comment]
Application is no longer supported because they removed api access to music...

**Comment by Snugface** [comment]
VK made version("v") a mandatory parameter with every API request.
You need to manually edit the files you downloaded(such as "main.py" or "PostParser.py") to include the version parameter.
For that find all occurrences of "call_api" function and add the following where necessary:
```
,  ("v",4.4)
```
add it before
```
], self.args"
```
For example:
```
call_api("audio.getById", [("audios", request)], self.args)
```
...has to be changed to:
```
call_api("audio.getById", [("audios", request), ("v",4.4) ], self.args)
```

And yes, I am aware that audio API is broken. Everything else appears to be working fine.

Quick question:
Any way to read the output in a comprehensive manner? Currently I get hundreds of folders with multiple items in them. And that's great. But there is no way to actually browse through them all on one page.
Hell, I can't even look at a single whole post - I need to open 3-4 different files for that.

**Comment by Rast1234** [comment]
Wow, you bothered to describe the patch. You just could send a pull request :) I think i'll fix it according to your instructions, thanks.

Not so quick answer (sorry): i did not think of a way to browse downloaded data visually because i didn't need it back then. You can try website snapshotting software like HTTrack and Teleport. Alternatively, write some HTML/JS which rely on saved data, but it is going to get complicated very fast.

**Comment by Snugface** [comment]
I'm glad to know that you are still active, even if takes you a while to reply :)
It is my greatest pleasure to have received an answer. And to know that you support the international VK community.

The patch is no big deal, really. I did worse, with some linux kernel drivers.
I am however pretty dreadful with web dev. Still, I have an interesting idea. My main goal here is to preserve my wall, not much else.
If I save it directly from my browser, it does so without saving the images. Which is quite a bummer, as you might understand.
However, your script takes care of that well enough(of saving the images). So what I'm thinking of is to simply merge the two approaches.

Your script saves the posts with their original IDs, correct?

**Comment by Rast1234** [comment]
I save posts according to their IDs, right. I also save photos by their name from URL. For docs i make filename from title and for audio i make name as "{artist} - {title}.mp3".

Before trying to mix script's output and browser-saved page, i suggest you to try HTTrack or Teleport because that's the reason they exist: to capture pages as they are displayed, even with hyperlinks for some given depth.

**Comment by Rast1234** [comment]
I abandoned this project and implemented a replacement in C#. It supports more stuff, works much faster and more reliable in general. Still needs some polishing and docs though. See description if you are interested.
